import { describe, expect, it } from "vitest";
import {
  AUTO_GENERATED_TAG,
  buildContextSummary,
  buildGeneratePrompt,
  generateFallbackContent,
  generatePlan,
  isEnriched,
  type WikiPageLike,
} from "./wikiEngine";

const genericPage = (title: string): WikiPageLike => ({
  title,
  tags: [AUTO_GENERATED_TAG, "wiki-engine"],
  content: `# ${title}\n\n> No wiki page covers "${title}"\n\n## Overview\nThis page provides comprehensive documentation for ${title.toLowerCase()}.\n\n## Key Information\n- Information pending review.\n\n---\n*Auto-generated by Wiki Engine — review and refine this content.*`,
});

describe("generatePlan", () => {
  it("plans a create for every uncovered suggested topic on an empty wiki", () => {
    const context = buildContextSummary([], [], []);
    const plan = generatePlan(context);

    expect(plan.length).toBeGreaterThan(0);
    expect(plan.every((p) => p.action === "create")).toBe(true);
    expect(plan.map((p) => p.title)).toContain("Company Overview");
  });

  it("does NOT re-plan a topic whose page is real, human-authored content", () => {
    const context = buildContextSummary(
      [
        {
          title: "Company Overview",
          tags: ["seed"],
          content:
            "Seridian is a cloud infrastructure and application development consultancy serving startups and small teams with fixed-scope engagements, transparent pricing, and cash-before-work delivery timelines.",
        },
      ],
      [],
      [],
    );
    const plan = generatePlan(context);
    expect(plan.find((p) => p.title === "Company Overview")).toBeUndefined();
  });

  it("regression: re-plans a topic stuck as a generic auto-generated placeholder", () => {
    // This is the exact bug: once the engine's own fallback template exists
    // (long enough to clear the old 150-char thin-content check), the old
    // logic considered it permanently covered and never revisited it.
    const context = buildContextSummary([genericPage("Company Overview")], [], []);
    expect(context.pageContents[0].excerpt.length).toBeGreaterThan(150);

    const plan = generatePlan(context);
    const item = plan.find((p) => p.title === "Company Overview");
    expect(item).toBeDefined();
    expect(item!.action).toBe("update");
    expect(item!.reason).toMatch(/generic auto-generated placeholder/);
  });

  it("re-plans a placeholder page even with zero memories, once real facts exist elsewhere in the wiki", () => {
    const context = buildContextSummary(
      [
        genericPage("Client Services"),
        {
          title: "Seridian — Company",
          tags: ["seed"],
          content: "Seridian is a cloud infrastructure and application development consultancy.",
        },
      ],
      [], // 0 memories — matches the bug report exactly
      [{ name: "Alex Rivera", company: "Northwind Labs" }],
    );

    expect(context.memorySnippets).toHaveLength(0);
    expect(context.companyFacts.length).toBeGreaterThan(0);

    const plan = generatePlan(context);
    expect(plan.find((p) => p.title === "Client Services")?.action).toBe("update");
  });

  it("stops re-planning a placeholder once it's been enriched with a known client", () => {
    const enriched: WikiPageLike = {
      title: "Company Overview",
      tags: [AUTO_GENERATED_TAG, "wiki-engine"],
      content:
        "# Company Overview\n\nOur flagship client is Northwind Labs, and we've partnered with them on a multi-quarter cloud migration and platform modernization engagement.",
    };
    const context = buildContextSummary(
      [enriched],
      [],
      [{ name: "Northwind Labs", company: "Northwind Labs" }],
    );
    expect(isEnriched(context.pageContents[0], context)).toBe(true);
    expect(generatePlan(context).find((p) => p.title === "Company Overview")).toBeUndefined();
  });

  it("still catches genuinely thin pages regardless of tags", () => {
    const context = buildContextSummary(
      [{ title: "Company Overview", tags: ["seed"], content: "TBD" }],
      [],
      [],
    );
    const item = context.pageContents ? generatePlan(context).find((p) => p.title === "Company Overview") : undefined;
    expect(item?.reason).toMatch(/thin content/);
  });
});

describe("buildGeneratePrompt / generateFallbackContent", () => {
  it("grounds both the LLM prompt and the fallback content in real company facts, not just memories", () => {
    const context = buildContextSummary(
      [
        genericPage("Company Overview"),
        {
          title: "Seridian — Company",
          tags: ["seed"],
          content: "Seridian is a cloud infrastructure and application development consultancy.",
        },
      ],
      [],
      [{ name: "Alex Rivera", company: "Northwind Labs" }],
    );
    const plan = generatePlan(context).find((p) => p.title === "Company Overview")!;

    const prompt = buildGeneratePrompt(plan, context);
    expect(prompt).toContain("REAL COMPANY FACTS");
    expect(prompt).toContain("cloud infrastructure");
    expect(prompt).toContain("Northwind Labs");

    const fallback = generateFallbackContent(plan, context);
    expect(fallback).toContain("cloud infrastructure");
    expect(fallback).toContain("Northwind Labs");
  });
});
