#!/usr/bin/env bun
/**
 * Isolated CLI test for the Wiki Engine core pipeline (src/lib/wikiEngine.ts).
 * No browser, no Convex, no React — pure function calls against fixture data.
 *
 * Run:  bun run scripts/wiki-engine-cli.ts
 *       bun run scripts/wiki-engine-cli.ts --llm   (also runs the real local
 *                                                    T5 model, same one the
 *                                                    browser uses — downloads
 *                                                    ~60MB on first run)
 *
 * Reproduces the reported bug: once the Wiki Engine's own generic fallback
 * pages exist (tagged "auto-generated"), the old plan logic considered every
 * topic permanently "covered" — the pipeline reported 0 improvements forever,
 * even with 0 memories and unused real company data sitting in other pages.
 */

import {
  buildContextSummary,
  buildGeneratePrompt,
  generateFallbackContent,
  generatePlan,
  type ClientLike,
  type MemoryLike,
  type WikiPageLike,
} from "../src/lib/wikiEngine";

// Fixture: the exact state from the bug report — 10 pages (all generic
// fallback templates from a prior run), 0 memories, 3 clients. Two of the
// 10 pages ALSO happen to carry real Seridian content elsewhere in the
// wiki, to prove that info now gets pulled in.
const genericPage = (title: string): WikiPageLike => ({
  title,
  tags: ["auto-generated", "wiki-engine"],
  content: `# ${title}\n\n> No wiki page covers "${title}"\n\n## Overview\nThis page provides comprehensive documentation for ${title.toLowerCase()}.\n\n## Key Information\n- Information pending review.\n\n## Related Clients\n- Client data pending integration.\n\n## Additional Notes\n- Cross-reference with other wiki pages as needed\n- Update regularly as information evolves\n\n---\n*Auto-generated by Wiki Engine — review and refine this content.*`,
});

const topics = [
  "Company Overview",
  "Client Services",
  "Technology Stack",
  "Team & Roles",
  "Pricing & Plans",
  "Project Workflow",
  "Security & Compliance",
  "API Documentation",
  "Onboarding Guide",
  "Troubleshooting",
];

const wikiPages: WikiPageLike[] = [
  ...topics.map(genericPage),
  {
    title: "Seridian — Company",
    tags: ["company", "seridian", "seed"],
    content:
      "Seridian is a cloud infrastructure and application development consultancy. We partner with organizations to architect resilient systems, ship modern applications, and make technical decisions that last. Positioning: practical consulting, not slide decks.",
  },
];

const memories: MemoryLike[] = [];

const clients: ClientLike[] = [
  { name: "Alex Rivera", company: "Northwind Labs" },
  { name: "Priya Shah", company: "Blueprint Robotics" },
  { name: "Jordan Kim", company: "Fenwick Analytics" },
];

function section(title: string) {
  console.log(`\n${"=".repeat(60)}\n${title}\n${"=".repeat(60)}`);
}

section("BEFORE FIX (simulated): old coverage check = title match only");
{
  const covered = topics.filter((t) =>
    wikiPages.some((p) => p.title.toLowerCase().includes(t.toLowerCase().includes("&") ? t.split(" ")[0].toLowerCase() : t.toLowerCase())),
  );
  console.log(`All ${covered.length}/${topics.length} topics have a matching-titled page.`);
  console.log(`Old generatePlan() would report 0 "create" items and, since each`);
  console.log(`fallback page is padded past 150 chars, 0 "update" items either.`);
  console.log(`=> Plan: 0 improvements identified (matches the bug report exactly).`);
}

section("AFTER FIX: generatePlan() with isEnriched() placeholder detection");
const context = buildContextSummary(wikiPages, memories, clients);
console.log(
  `Scanned: ${context.pageTitles.length} pages, ${context.memorySnippets.length} memories, ${context.clientNames.length} clients, ${context.companyFacts.length} real company facts`,
);

const plan = generatePlan(context);
console.log(`Plan: ${plan.length} improvements identified\n`);
for (const item of plan) {
  console.log(`  [${item.action}] ${item.title} — ${item.reason}`);
}

if (plan.length === 0) {
  console.error("\nFAIL: expected the fix to surface placeholder pages for update.");
  process.exit(1);
}

section("Generated content (fallback generator, no LLM download needed for CLI speed)");
const first = plan[0];
const content = generateFallbackContent(first, context);
console.log(`--- ${first.title} ---\n${content}\n`);

const mentionsRealCompanyInfo = content.toLowerCase().includes("cloud infrastructure") || content.toLowerCase().includes("consultancy");
const mentionsClient = clients.some((c) => content.includes(c.name));
console.log(`Contains real company info from other pages: ${mentionsRealCompanyInfo}`);
console.log(`Contains a real client name: ${mentionsClient}`);

section("Prompt that would go to the local LLM (for inspection)");
console.log(buildGeneratePrompt(first, context));

if (!mentionsRealCompanyInfo) {
  console.error("\nFAIL: fallback content still doesn't include real company facts.");
  process.exit(1);
}

console.log("\nOK — plan re-triggers on generic placeholders, and generation is grounded in real company data.\n");

if (process.argv.includes("--llm")) {
  section("Real local LLM pass (same model + prompt the browser uses)");
  console.log("Loading Xenova/T5-small via @huggingface/transformers (Node/Bun-compatible)...");
  const { pipeline } = await import("@huggingface/transformers");
  const llm = await pipeline("text2text-generation", "Xenova/T5-small");
  const prompt = buildGeneratePrompt(first, context);
  const result = await llm(prompt, { max_new_tokens: 512, temperature: 0.7 });
  const generated = (result as Array<{ generated_text: string }>)[0]?.generated_text ?? "";
  console.log(`--- LLM output for "${first.title}" ---\n${generated}\n`);
  console.log(`Length: ${generated.length} chars (validation threshold is 50)`);
}
